name: CI-branch-pr

# this will disable concurrent builds per branch
concurrency:
  group: default  # only one branch built at-a-time
  cancel-in-progress: false

# build has to be on branch push so github.ref contains the branch name that can be passed to Spinnaker
on:
  pull_request:
    branches:
    - main

  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: 
        required: true
    branches-ignore:
      - main

jobs:

  build:
    runs-on:
      - ubuntu-22.04

    env:
      RELEASE_REGISTRY: kumo-docker-release-local.artylab.expedia.biz

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo '$GITHUB_CONTEXT'
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo '$JOB_CONTEXT'
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo '$STEPS_CONTEXT'
    # - name: print branch name
    #   run:  echo "branch name is ${{ github.event.pull_request.head.ref }}"